# Generated by Django 5.0.4 on 2024-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100)),
                ('himageb', models.ImageField(upload_to='images')),
                ('hlocation', models.TextField()),
                ('hrating', models.FloatField()),
                ('hdesc', models.TextField()),
            ],
        ),
    ]
