# Generated by Django 5.0.4 on 2024-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0002_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hprice',
            field=models.FloatField(default=6999),
            preserve_default=False,
        ),
    ]
